### ISSUE TITLE
Error setting up the Component (worked before updating to 0.61.1)

### ISSUE THREAD

**Issue by thundergreen** [hmn/home-assistant-config#20]
```
2018-01-23 00:28:42 ERROR (SyncWorker_19) [custom_components.media_player.ps4] Error decoding ps4 json : Expecting property name enclosed in double quotes: line 1 column 3 (char 2)
```

config:

```yaml
media_player:
  - platform: ps4
    name: "PS4"
    host: 192.168.1.8
    local_store: games
```
